const Events = {
	// 浏览器不支持WebRTC
	WEBRTC_NOT_SUPPORT : 'WEBRTC_NOT_SUPPORT',
	// ICE候选收集过程中发生错误
	WEBRTC_ICE_CANDIDATE_ERROR : 'WEBRTC_ICE_CANDIDATE_ERROR',
	// Offer/Answer交换失败
	WEBRTC_OFFER_ANSWER_EXCHANGE_FAILED:'WEBRTC_OFFER_ANSWER_EXCHANGE_FAILED',
	// 接收到远程媒体流
	WEBRTC_ON_REMOTE_STREAMS:'WEBRTC_ON_REMOTE_STREAMS',
	// 获取到本地媒体流
	WEBRTC_ON_LOCAL_STREAM:'WEBRTC_ON_LOCAL_STREAM',
	// WebRTC连接状态发生变化
	WEBRTC_ON_CONNECTION_STATE_CHANGE:'WEBRTC_ON_CONNECTION_STATE_CHANGE',
	// 数据通道成功打开
	WEBRTC_ON_DATA_CHANNEL_OPEN:'WEBRTC_ON_DATA_CHANNEL_OPEN',
	// 数据通道关闭
	WEBRTC_ON_DATA_CHANNEL_CLOSE:'WEBRTC_ON_DATA_CHANNEL_CLOSE',
	// 数据通道发生错误
	WEBRTC_ON_DATA_CHANNEL_ERR:'WEBRTC_ON_DATA_CHANNEL_ERR',
	// 接收到数据通道消息
	WEBRTC_ON_DATA_CHANNEL_MSG:'WEBRTC_ON_DATA_CHANNEL_MSG',
	// 捕获媒体流失败
	CAPTURE_STREAM_FAILED:'CAPTURE_STREAM_FAILED',
};

export default Events;